#' Read an exposure profile 
#'
#' Read a single exposure profile at 'pathtofile'
#'
#' @param pathtofile the path where the exposure profile is found
#'
#' @importFrom attempt attempt
#'
#' @return the exposure profile
#' @export
readSingleExpProfile <- function(pathtofile){
  if (tools::file_ext(pathtofile) == "csv") {
    profile <- read.csv(pathtofile, header = FALSE) %>% attempt::attempt(msg=paste0("Could not read file ",pathtofile))
  } else {
    profile <- read.table(pathtofile) %>% attempt::attempt(msg=paste0("Could not read file ",pathtofile))
  }
  
  if (class(profile)=="try-error")
    profile <- NULL
  
  checkedProfile <- checkProfile(profile)
  
    if (length(checkedProfile) > 1)
      colnames(profile) <- c("V1", "V2")
    else
      profile <- checkedProfile

  return(profile)
}


#' Read exposure profiles
#' 
#' Read several exposure profiles at their corresponding pathes at 'pathtofiles'
#'
#' @param pathtofiles 
#' @param profileNames 
#'
#' @return list of exposure profiles
#' @export
readExpProfiles <- function(pathtofiles, profileNames=NA){
  if ( any(sapply(profileNames, is.na)) ) {
    profileNames <- basename(pathtofiles) %>% 
      tools::file_path_sans_ext()
  } else {
    profileNames <- profileNames
  }
  raw_profiles <- lapply(pathtofiles, readSingleExpProfile)
  names(raw_profiles) <- profileNames
  
  # any incorrect profiles?
  flagCorrect <- do.call(c, lapply(raw_profiles,function(x) length(x)!=0))
  raw_profiles <- raw_profiles[flagCorrect]
  
  
  return(raw_profiles)
}


#' checkProfile
#'
#' @param p the exposure profile 
#'
#' @return the profile or NULL if not correct
#' @noRd
checkProfile <- function(p){
  # check if has content
  if (!length(p)){
    out <- "File is empty"
    warning(out)
    return(NULL)
  }
  
  
  
  # check if two columns
  if (ncol(p) != 2){
    out <- "File is not a plain-text file with two columns."
    warning(out)
    return(NULL)
  }
  
  # check if columns give numeric data
  colClasses <- c(class(p[,1]), class(p[,1]))
  acceptedClass <- !any(!(colClasses %in% c("numeric", "integer")))
  if (!acceptedClass){
    out <- "The columns are neither 'numeric' nor 'integers'."
    warning(out)
    return(NULL)
  }
  
  
  # check if the time column is increasing
  timeCol <- p[,1]
  increasing <- !any(diff(timeCol)<=0)
  if (!increasing){
    out <- "Time is not increasing."
    warning(out)
    return(NULL)
  }
  
  out <- p
  return(out)
  
}



#' Adds padding to a exposure profile
#' 
#' Adds padding of zero concentration to the start and end of the FOCUS profile equal to the windowLength
#' minus 1 dt step. Thus the first and last windows have minimum (but not zero) time with non-zero exposure.
#'
#' @param profile  FOCUS profile before any padding
#' @param dt the timesteps at which to add to the time and conc vectors, (days), smaller means more accurate
#' @param windowLength the length of each time window
#'
#' @return an exposure profile with padding
#' @export
add_padding <- function(profile, dt, windowLength) {

  # V1 and V2 agrees with names generated by read.table
  # padding at start:
  V1 <- seq(-(windowLength-dt), -dt, by=dt) # -ve times so input profile times aren't shifted
  V2 <- rep(0, length(V1)) # pad concentrations with zeros to match -ve times
  ps <- data.frame(V1, V2) # turn padding times and (zero) concs into a frame
  profile <- rbind(ps, profile) # append this padding to the start of the profile
  
  # padding at end:
  endTime = profile[length(profile[,1]),1] # last timepoint in the profile
  V1 <- seq(endTime + dt, endTime + windowLength - dt, by=dt) # times run from endTime onwards according to windowLength
  pe <- data.frame(V1, V2)
  profile <- rbind(profile, pe) # append to the end
  return(profile)
  
}


#' Plot exposure profile
#'
#' @param data the exposure profile data loaded with 'readExpProfiles'
#' @param x the data column plotted on the x-axis
#' @param y the data column plotted on the y-axis
#' @param title the plot title
#' @param xlab the label of the x-axis
#' @param ylab the label of the y-axis
#'
#' @return a ggplot object of exposure profiles
#' @export
plotExpProfiles <- function(data, x="V1", y="V2", title=NULL, xunit=NA, yunit=NA){#xlab="Time (days)", ylab="External conc."){
  
  xlab0 <- "Time"
  ylab0 <- "External conc."
  xlab <- ifelse( is.na(xunit), xlab0, paste0(xlab0," (",xunit,")"))
  ylab <- ifelse( is.na(yunit), ylab0, paste0(ylab0," (",yunit,")"))
  
  ggplot() + 
    geom_line(data=data, mapping=aes(data[,x], data[,y])) +
    labs(y = ylab, x = xlab) +
    ggtitle(title)
}

